import { useEffect, useMemo, useRef, useState } from "react"
import { ChevronRight, CircleStop, Lightbulb, Music, Play, Plus, Save, SlidersHorizontal, Sparkles, Trash2, Upload } from "lucide-react"
import { useSession } from "../app/session"
import { ApiError } from "../api/client"
import { Badge, Button, Card, EmptyState, InlineActionStatus, Modal, PageHeader, fieldClass } from "../components/ui"
import type { ShowCue, ShowScore } from "../api/types"
import { mapImportedShow, parseShowImport, type ImportedShow } from "./show-import"

const lightOptions = [["off", "熄灯"], ["left", "左灯常亮"], ["right", "右灯常亮"], ["both", "双灯常亮"], ["left_blink", "左灯闪烁"], ["right_blink", "右灯闪烁"], ["both_blink", "双灯闪烁"], ["alternate", "交替闪烁"]] as const
const motionPresets = [{ label: "前进", value: { linear_x: .3 } }, { label: "后退", value: { linear_x: -.3 } }, { label: "左移", value: { linear_y: .3 } }, { label: "右移", value: { linear_y: -.3 } }, { label: "左转", value: { angular_z: 1.2 } }, { label: "右转", value: { angular_z: -1.2 } }] as const
const fresh = (): ShowScore => ({ id: "", name: "未命名演出", score: { bpm: 120, beats_per_bar: 4, ticks_per_beat: 2, robot_ids: [], tracks: {} } })
const blankTrack = () => ({ motion: [] as ShowCue[], lights: [] as ShowCue[] })
type Notice = { tone: "info" | "success" | "error" | "warning"; title: string; detail?: string }

function errorText(error: unknown) {
  if (error instanceof ApiError && error.details) {
    const detail = typeof error.details === "object" ? Object.entries(error.details as Record<string, unknown>).map(([key, value]) => `${key}: ${String(value)}`).join("；") : String(error.details)
    return `${error.message}（${detail}）`
  }
  return error instanceof Error ? error.message : "请求没有完成，请检查中心服务连接后重试。"
}

export function ShowPage() {
  const { api } = useSession(); const [library, setLibrary] = useState<ShowScore[]>([]); const [show, setShow] = useState<ShowScore>(fresh); const [robots, setRobots] = useState<Awaited<ReturnType<NonNullable<typeof api>["robots"]>>>([]); const [activeRobot, setActiveRobot] = useState(""); const [notice, setNotice] = useState<Notice>({ tone: "info", title: "等待编排", detail: "选择一辆或多辆在线车辆，再添加动作与灯光。" }); const [busy, setBusy] = useState<"save" | "play" | "abort" | null>(null); const [dirty, setDirty] = useState(false); const [audioName, setAudioName] = useState(""); const [importDraft, setImportDraft] = useState<ImportedShow | null>(null); const [importMapping, setImportMapping] = useState<Record<string, string>>({}); const audio = useRef<AudioBuffer | null>(null); const importInput = useRef<HTMLInputElement | null>(null)
  const load = async () => { if (!api) return; const [items, cars] = await Promise.all([api.shows(), api.robots()]); setLibrary(items); setRobots(cars) }
  useEffect(() => { void load().catch(e => setNotice({ tone: "error", title: "演出数据读取失败", detail: errorText(e) })) }, [api])
  useEffect(() => { if (!activeRobot || !show.score.robot_ids.includes(activeRobot)) setActiveRobot(show.score.robot_ids[0] || "") }, [activeRobot, show.score.robot_ids])
  const selected = useMemo(() => robots.filter(r => show.score.robot_ids.includes(r.id)), [robots, show.score.robot_ids])
  const track = show.score.tracks[activeRobot] || blankTrack(); const tickMs = Math.round(60000 / show.score.bpm / 2)
  const change = (fn: (value: ShowScore) => ShowScore) => { setDirty(true); setShow(value => fn(value)) }
  const patchTrack = (robotId: string, patch: Partial<ReturnType<typeof blankTrack>>) => change(value => ({ ...value, score: { ...value.score, tracks: { ...value.score.tracks, [robotId]: { ...(value.score.tracks[robotId] || blankTrack()), ...patch } } } }))
  const toggleRobot = (id: string) => change(value => { const ids = value.score.robot_ids.includes(id) ? value.score.robot_ids.filter(x => x !== id) : [...value.score.robot_ids, id]; const tracks = { ...value.score.tracks }; ids.forEach(x => tracks[x] ||= blankTrack()); return { ...value, score: { ...value.score, robot_ids: ids, tracks } } })
  const appendMotion = (values: Partial<ShowCue> = {}) => { if (!activeRobot) return; patchTrack(activeRobot, { motion: [...track.motion, { at_tick: nextTick(track.motion), duration_ticks: 2, linear_x: 0, linear_y: 0, angular_z: 0, ...values }] }) }
  const appendLight = (effect = "both") => { if (!activeRobot) return; patchTrack(activeRobot, { lights: [...track.lights, { at_tick: nextTick(track.lights), duration_ticks: 2, effect }] }) }
  const updateCue = (lane: "motion" | "lights", index: number, key: keyof ShowCue, raw: string) => patchTrack(activeRobot, { [lane]: track[lane].map((cue, i) => i === index ? { ...cue, [key]: key === "effect" ? raw : Number(raw) } : cue) })
  const removeCue = (lane: "motion" | "lights", index: number) => patchTrack(activeRobot, { [lane]: track[lane].filter((_, i) => i !== index) })
  const readImport = async (file?: File) => {
    if (!file) return
    try { const parsed = parseShowImport(JSON.parse(await file.text()), file.name.replace(/\.json$/i, "")); setImportDraft(parsed); setImportMapping(Object.fromEntries(parsed.score.robot_ids.map(alias => [alias, ""]))); setNotice({ tone: "info", title: "结构文件已解析", detail: `识别到 ${parsed.score.robot_ids.length} 个逻辑车辆，请完成现场车辆映射。` }) }
    catch (error) { setImportDraft(null); setNotice({ tone: "error", title: "导入文件无效", detail: errorText(error) }) }
  }
  const applyImport = () => {
    if (!importDraft) return
    try { const imported = mapImportedShow(importDraft, importMapping); setShow(imported); setDirty(true); setActiveRobot(imported.score.robot_ids[0] || ""); audio.current = null; setAudioName(imported.score.audio_name || ""); setImportDraft(null); setNotice({ tone: "success", title: "谱表已导入", detail: `已映射 ${imported.score.robot_ids.length} 辆现场车辆；检查后点击保存。` }) }
    catch (error) { setNotice({ tone: "warning", title: "车辆映射尚未完成", detail: errorText(error) }) }
  }
  const save = async () => {
    if (!api) return setNotice({ tone: "error", title: "尚未连接中心服务", detail: "请先完成连接，再保存谱表。" })
    if (!show.name.trim()) return setNotice({ tone: "warning", title: "还没有演出名称", detail: "填写名称后才能保存。" })
    if (show.score.robot_ids.length < 1) return setNotice({ tone: "warning", title: "先选择一辆车", detail: "选择至少一辆在线车辆后，才能保存和派发动作谱。" })
    setBusy("save"); setNotice({ tone: "info", title: "正在保存谱表", detail: "正在写入中心服务…" })
    try { const payload = { name: show.name.trim(), score: show.score }; const result = show.id ? await api.updateShow(show.id, payload) : await api.createShow(payload); setShow(result); setLibrary(items => [result, ...items.filter(item => item.id !== result.id)]); setDirty(false); setNotice({ tone: "success", title: "谱表已保存", detail: `“${result.name}”已进入演出库，可以开始派发。` }) }
    catch (error) { setNotice({ tone: "error", title: "保存失败", detail: errorText(error) }) }
    finally { setBusy(null) }
  }
  const play = async () => {
    if (!api) return setNotice({ tone: "error", title: "尚未连接中心服务", detail: "请先完成连接，再派发演出。" })
    if (!show.id || dirty) return setNotice({ tone: "warning", title: "请先保存最新修改", detail: "车辆只能执行已保存的谱表版本。" })
    setBusy("play"); setNotice({ tone: "info", title: "正在预加载车辆", detail: "等待所有车辆确认 ready，随后进入 5 秒倒计时。" })
    try { const buffer = audio.current; const offset = buffer ? await clockOffset(api) : 0; const result = await api.startShow(show.id); const start = Date.parse(String(result.start_at_utc)); if (buffer) { const context = new AudioContext(); await context.resume(); const source = context.createBufferSource(); source.buffer = buffer; source.connect(context.destination); source.start(context.currentTime + Math.max(.1, (start - (Date.now() + offset)) / 1000)) } setNotice({ tone: "success", title: "已派发，正在倒计时", detail: buffer ? `车辆将在 ${new Date(start).toLocaleTimeString()} 与音乐同时开始。` : `车辆将在 ${new Date(start).toLocaleTimeString()} 开始执行；本次不播放音乐。` }) }
    catch (error) { setNotice({ tone: "error", title: "演出未启动", detail: errorText(error) }) }
    finally { setBusy(null) }
  }
  const abort = async () => {
    if (!api || !show.id) return setNotice({ tone: "warning", title: "没有可终止的演出", detail: "请先保存并派发一份谱表。" })
    setBusy("abort"); setNotice({ tone: "info", title: "正在终止全组演出", detail: "正在向参与车辆发送停车与熄灯命令…" })
    try { const result = await api.abortShow(show.id); setNotice(result.ok ? { tone: "success", title: "全组已终止", detail: "已向参与车辆下发停车和熄灯命令。" } : { tone: "warning", title: "终止指令已发出", detail: "至少一辆车没有确认；请检查车辆在线状态。" }) }
    catch (error) { setNotice({ tone: "error", title: "终止请求失败", detail: errorText(error) }) }
    finally { setBusy(null) }
  }
  const selectShow = (id: string) => { const item = library.find(x => x.id === id); if (item) { setShow(item); setDirty(false); audio.current = null; setAudioName(item.score.audio_name || ""); setNotice({ tone: "info", title: "已载入谱表", detail: "可以直接派发；如果需要同步播放音乐，再重新选择本机文件。" }) } }
  const startDisabled = !show.id || dirty || busy !== null
  const startHint = !show.id ? "先保存谱表后才能派发" : dirty ? "有未保存修改，保存后才能派发" : audio.current ? "将同步派发车辆并播放本机音乐" : "未选择音乐：只执行车辆动作与灯光"
  const importAliases = importDraft?.score.robot_ids || []; const importTargets = importAliases.map(alias => importMapping[alias]).filter(Boolean); const importReady = importAliases.length > 0 && importTargets.length === importAliases.length && new Set(importTargets).size === importTargets.length
  return <div className="page-enter show-page"><PageHeader eyebrow="MUSIC-CUED OPEN-LOOP SHOW" title="演出编排" description="先选车，再按节拍安排动作与灯效。车辆只按时间轴执行，不使用 Nav2 校正位置。" actions={<><input ref={importInput} hidden type="file" accept=".json,application/json" onChange={event => { const file = event.target.files?.[0]; event.target.value = ""; void readImport(file) }} /><Button variant="secondary" disabled={busy !== null} onClick={() => importInput.current?.click()}><Upload />导入谱表</Button><Button variant="secondary" disabled={busy !== null} onClick={() => { setShow(fresh()); setDirty(false); audio.current = null; setAudioName(""); setNotice({ tone: "info", title: "已新建空白谱表", detail: "选择一辆或多辆车后，添加动作与灯光，再点击保存。" }) }}><Sparkles />新建</Button><Button variant="primary" loading={busy === "save"} loadingText="正在保存" disabled={busy !== null && busy !== "save"} onClick={() => void save()}><Save />{dirty || !show.id ? "保存谱表" : "已保存"}</Button></>} />
    <InlineActionStatus tone={notice.tone} title={notice.title} detail={notice.detail} onRetry={notice.tone === "error" && !busy ? () => void load().catch(error => setNotice({ tone: "error", title: "演出数据读取失败", detail: errorText(error) })) : undefined} />
    <div className="show-studio"><aside className="show-sidebar"><Card className="panel show-setup"><div className="panel-head"><div><h2>1. 演出设置</h2><p>一个小节固定 4 拍，每拍 2 格。</p></div><Music /></div><label>已有谱表<select className={fieldClass} value={show.id} onChange={e => selectShow(e.target.value)}><option value="">新建谱表</option>{library.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>演出名称<input className={fieldClass} value={show.name} onChange={e => change(v => ({ ...v, name: e.target.value }))} /></label><label className="bpm-field"><span>BPM <small>每格约 {tickMs} ms</small></span><input className={fieldClass} type="number" min="40" max="240" value={show.score.bpm} onChange={e => change(v => ({ ...v, score: { ...v.score, bpm: Number(e.target.value) } }))} /></label><label className="audio-picker"><span>本机音乐（可选）</span><input type="file" accept="audio/*" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { const context = new AudioContext(); audio.current = await context.decodeAudioData(await file.arrayBuffer()); await context.close(); setAudioName(file.name); change(v => ({ ...v, score: { ...v.score, audio_name: file.name } })); setNotice({ tone: "success", title: "音乐已预加载", detail: `已选中 ${file.name}；保存谱表后可以与车辆同步开始。` }) } catch (error) { audio.current = null; setAudioName(""); setNotice({ tone: "error", title: "音乐读取失败", detail: errorText(error) }) } }} /><strong>{audioName || "未选择，仍可直接执行动作"}</strong><small>音乐不是必需项；选择后才会按统一 UTC 时间播放。</small></label></Card>
      <Card className="panel show-vehicles"><div className="panel-head"><div><h2>2. 选择车辆</h2><p>单车可预演；多车会统一按同一 UTC 时刻启动。</p></div></div>{robots.map(robot => { const selectedNow = show.score.robot_ids.includes(robot.id); return <button type="button" className={`show-vehicle ${selectedNow ? "selected" : ""}`} key={robot.id} disabled={!robot.enabled || !robot.online} onClick={() => toggleRobot(robot.id)}><span className="vehicle-check">{selectedNow ? "✓" : ""}</span><span><strong>{robot.name}</strong><small>{robot.id}{robot.online ? " · 在线" : " · 离线"}</small></span></button> })}</Card></aside>
      <main className="show-main"><Card className="panel show-runbar"><div><Badge tone={show.id && !dirty ? "success" : "warning"}>{show.id && !dirty ? "已保存" : "未保存"}</Badge><strong>{show.score.robot_ids.length} 辆车 · {show.score.bpm} BPM · 半拍网格</strong><span>{startHint}</span></div><div className="show-run-actions"><Button variant="primary" loading={busy === "play"} loadingText="正在预加载" disabled={startDisabled} onClick={() => void play()}><Play />{audio.current ? "派发并播放" : "派发并开始"}</Button><Button variant="danger" loading={busy === "abort"} loadingText="正在终止" disabled={!show.id || busy !== null} onClick={() => void abort()}><CircleStop />全组终止</Button></div></Card>
        {!selected.length ? <EmptyState title="先选择参与演出的车辆" detail="选定一辆车后即可开始编排；多车时每辆车都有独立时间轴。" /> : <><Card className="panel show-robot-tabs"><div className="panel-head"><div><h2>3. 选择编排对象</h2><p>每辆车有相互独立的运动与灯光轨，二者可在同一拍并行。</p></div></div><div className="show-tab-list">{selected.map((robot, index) => <button type="button" key={robot.id} className={activeRobot === robot.id ? "active" : ""} onClick={() => setActiveRobot(robot.id)}><span>{String.fromCharCode(65 + index)}</span><strong>{robot.name}</strong><small>{trackCount(show.score.tracks[robot.id])} 个动作</small><ChevronRight /></button>)}</div></Card>
          <Card className="panel show-composer"><div className="panel-head"><div><h2>{selected.find(x => x.id === activeRobot)?.name} 的时间轴</h2><p>第 0 格是时间轴起点；有音乐时也是音乐起拍。推荐用 2、4 或 8 格组成完整动作句。</p></div><SlidersHorizontal /></div><div className="show-quick-actions"><section><h3>快速添加运动</h3><div>{motionPresets.map(item => <Button key={item.label} variant="secondary" size="sm" onClick={() => appendMotion(item.value)}><Plus />{item.label} 1 拍</Button>)}</div></section><section><h3>快速添加灯效</h3><div>{lightOptions.slice(1, 5).map(([value, label]) => <Button key={value} variant="ghost" size="sm" onClick={() => appendLight(value)}><Lightbulb />{label}</Button>)}</div></section></div><div className="show-lanes"><CueLane title="运动轨" icon="↔" empty="点击上方预设，添加前进、侧移或旋转。" cues={track.motion} motion tickMs={tickMs} onAdd={() => appendMotion()} onChange={(i, k, v) => updateCue("motion", i, k, v)} onRemove={i => removeCue("motion", i)} /><CueLane title="灯光轨" icon="✦" empty="点击上方灯效，灯光可与运动同时发生。" cues={track.lights} tickMs={tickMs} onAdd={() => appendLight()} onChange={(i, k, v) => updateCue("lights", i, k, v)} onRemove={i => removeCue("lights", i)} /></div></Card></>}</main></div>
    <Modal open={Boolean(importDraft)} title="映射结构文件中的车辆" onClose={() => { setImportDraft(null); setImportMapping({}) }} footer={<><Button onClick={() => { setImportDraft(null); setImportMapping({}) }}>取消</Button><Button variant="primary" disabled={!importReady} onClick={applyImport}>应用导入</Button></>}>
      {importDraft && <div className="form-stack"><InlineActionStatus tone="info" title={`已读取“${importDraft.name}”`} detail={`${importDraft.score.bpm} BPM · ${importAliases.length} 个逻辑车辆。结构文件只提供 car_1、car_2 等角色，不直接绑定现场设备。`} />{importAliases.map(alias => <label key={alias}><span>{alias} · {trackCount(importDraft.score.tracks[alias])} 个动作 → 现场车辆</span><select className={fieldClass} value={importMapping[alias] || ""} onChange={event => setImportMapping(value => ({ ...value, [alias]: event.target.value }))}><option value="">请选择实际车辆</option>{robots.filter(robot => robot.enabled).map(robot => { const occupied = Object.entries(importMapping).some(([otherAlias, robotId]) => otherAlias !== alias && robotId === robot.id); return <option key={robot.id} value={robot.id} disabled={!robot.online || occupied}>{robot.name} · {robot.id}{robot.online ? "" : " · 离线"}</option> })}</select></label>)}{importAliases.length > 1 && new Set(importTargets).size < importTargets.length && <div className="form-error">同一辆现场车辆不能同时映射到多个逻辑车辆。</div>}<small className="show-import-hint">支持包装格式 <code>{`{ "name": "...", "score": { ... } }`}</code>，也支持直接以 bpm、robot_ids、tracks 为根节点的 JSON。</small></div>}
    </Modal></div>
}

function CueLane({ title, icon, empty, cues, motion, tickMs, onAdd, onChange, onRemove }: { title: string; icon: string; empty: string; cues: ShowCue[]; motion?: boolean; tickMs: number; onAdd(): void; onChange(i: number, k: keyof ShowCue, v: string): void; onRemove(i: number): void }) { return <section className="show-lane"><header><span>{icon}</span><div><strong>{title}</strong><small>{motion ? "速度持续到下一条命令或本动作结束" : "灯效与运动完全独立"}</small></div><Button size="sm" variant="ghost" onClick={onAdd}><Plus />添加</Button></header>{!cues.length ? <p className="show-lane-empty">{empty}</p> : <div className="show-cue-list">{cues.map((cue, i) => <article key={i}><div className="cue-timing"><b>第 <input type="number" value={cue.at_tick} onChange={e => onChange(i, "at_tick", e.target.value)} /> 格</b><span>{(cue.at_tick * tickMs / 1000).toFixed(2)} s · 持续 <input type="number" value={cue.duration_ticks} onChange={e => onChange(i, "duration_ticks", e.target.value)} /> 格</span></div>{motion ? <div className="cue-values"><label>前后<input type="number" step=".01" value={cue.linear_x || 0} onChange={e => onChange(i, "linear_x", e.target.value)} /></label><label>横移<input type="number" step=".01" value={cue.linear_y || 0} onChange={e => onChange(i, "linear_y", e.target.value)} /></label><label>转向<input type="number" step=".1" value={cue.angular_z || 0} onChange={e => onChange(i, "angular_z", e.target.value)} /></label></div> : <select className={fieldClass} value={cue.effect} onChange={e => onChange(i, "effect", e.target.value)}>{lightOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>}<Button size="sm" variant="ghost" className="cue-delete" onClick={() => onRemove(i)} aria-label="删除动作"><Trash2 /></Button></article>)}</div>}</section> }
function nextTick(cues: ShowCue[]) { return cues.reduce((latest, cue) => Math.max(latest, cue.at_tick + cue.duration_ticks), 0) }
function trackCount(track?: { motion: ShowCue[]; lights: ShowCue[] }) { return (track?.motion.length || 0) + (track?.lights.length || 0) }
async function clockOffset(api: NonNullable<ReturnType<typeof useSession>["api"]>) { const samples: Array<{ rtt: number; offset: number }> = []; for (let i = 0; i < 3; i += 1) { const sent = Date.now(); const server = await api.serverTime(); const received = Date.now(); samples.push({ rtt: received - sent, offset: server.epoch_ms - (sent + received) / 2 }) } samples.sort((a, b) => a.rtt - b.rtt); return samples[0].offset }
